# Utiliser une image de base appropriée, par exemple python:3.9
FROM python:3.9

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers requirements.txt et main.py dans le conteneur
COPY requirements.txt requirements.txt
COPY main.py main.py

# Installer les dépendances
RUN pip install -r requirements.txt

# Exposer le port utilisé par l'application
EXPOSE 8002

# Démarrer l'application avec uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
